[package]
name = "rstdms"
version = "0.1.0"
authors = ["Alex Anderson <anderson.alexj@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
num = "0.2.0"
num-traits = "0.2"
num-derive = "0.2"
bitflags = "*"